remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Frank Coolen
description: Frank Coolen's personal website
show_downloads: false
